name: CSharp_pipeline

on:
  push:
    branches:
      - news

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repo
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install dependencies with NuGet
        run: |
          dotnet restore
          
      - name: Check style project
        run: |
          dotnet tool install --global dotnet-format
          dotnet format --check
