name: CSharp_pipeline

on:
  push:
    branches:
      - news

jobs:
  checkstyle_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build

      - name: Run style analyzer
        run: dotnet format --check
