name: CSharp_Syntax_Check

on:
  push:
    branches:
      - main
      - development

jobs:
  syntax_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Install Roslyn Analyzers
        run: dotnet tool install -g Microsoft.CodeAnalysis.NetAnalyzers

      - name: Build and Analyze
        run: |
          dotnet build MySolution.sln
          dotnet analyze MySolution.sln
